### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-2-evaluacion-intermedia-marinacendon#1]
Hola @marinacendon, quieres terminar el ejercicio antes de que te lo corrija?

**Comment by marinacendon** [comment]
Sí!!! Gracias Lo termino hoy por la tarde, si?

**Comment by marinacendon** [comment]
@migueldelmazo , la he subido pero se que soy incapaz de hacerla sola. La he podido terminar gracias a todo lo que anoté del repaso de la evaluación. Pero yo sigo sin verle ni pies ni cabeza a JS :(.

**Comment by migueldelmazo** [comment]
El código está muy bien!!! Enhorabuena!!!
